### ISSUE TITLE
The kp setting for ankle roll and ankle pitc

### ISSUE THREAD

**Issue by lequn-F** [roboterax/humanoid-gym#26]
In the code, the kp setting for ankle roll and ankle pitch is 15, which completely fails to track the desired position. However, in the paper, the curves in Mujoco and on the real machine can track quite perfectly. I would like to ask if such a small kp setting is unique to Isaacgym. When transferring to a real robot, do these two joints also fail to track the desired position as they do in the simulation?

**Comment by zlw21gxy** [comment]
We employ an ankle pitch of 15 for two principal reasons. Firstly, the ankle motor is a smaller motor in contrast to others, and its torque limit is approximately one-tenth of that of other larger ones. Secondly, we conduct system identification. When a fixed sine wave is provided, the joint trajectory on the real robot is calibrated to Mujoco and IsaacGym. It should be noted that our comparison is not founded on the target joint position (action) and the actual position. They will not be equivalent due to factors such as gravity and friction. Our comparison is based on the response joint position. This implies that when the same actions are imparted to the real robot and the robot in the simulator, their behaviors are similar.

**Comment by lequn-F** [comment]
I see, thank you for your response.

**Comment by WeixianLin-cc** [comment]
> We employ an ankle pitch of 15 for two principal reasons. Firstly, the ankle motor is a smaller motor in contrast to others, and its torque limit is approximately one-tenth of that of other larger ones. Secondly, we conduct system identification. When a fixed sine wave is provided, the joint trajectory on the real robot is calibrated to Mujoco and IsaacGym. It should be noted that our comparison is not founded on the target joint position (action) and the actual position. They will not be equivalent due to factors such as gravity and friction. Our comparison is based on the response joint position. This implies that when the same actions are imparted to the real robot and the robot in the simulator, their behaviors are similar.

Thank you for developing such an excellent project, could you please describe in detail on how to perform comparison of the joint position response?
