### ISSUE TITLE
I can't evaluate the Trained PPO Policy 'v1'

### ISSUE THREAD

**Issue by caixukun1234** [roboterax/humanoid-gym#27]
Dear author：

I run this command:
python scripts/play.py --task=humanoid_ppo --run_name v1
But it doesn't seem to be running correctly.
Can you tell me how to solve this problem?
<img width="1184" alt="微信图片_20240727171546" src="https://github.com/user-attachments/assets/59c0ff5c-d815-4e86-b89e-1a912e898ae3">

**Comment by zlw21gxy** [comment]
Does it display the Isaac GUI and render the robot's walking in the simulator? If so, I would say that you have evaluated it accurately. The issue of 0 episodes occurs as we have not executed sufficient steps to reach the end of the episodes. This is because I intended to accelerate the play. If you desire, you can modify `stop_state_log` in play.py.
