### ISSUE TITLE
why the env_frictions and body_mass term in privileged_obs_buf is zero?

### ISSUE THREAD

**Issue by Zhangxiaof001** [roboterax/humanoid-gym#30]
`self.env_frictions = torch.zeros(self.num_envs, 1, dtype=torch.float32, device=self.device)
self.body_mass = torch.zeros(self.num_envs, 1, dtype=torch.float32, device=self.device, requires_grad=False)`
No value was found anywhere else in the source code.

**Comment by zlw21gxy** [comment]
Thank you for pointing out the issue. The problem was caused by these variables being initialized to zero without any subsequent assignment of actual values, which led to them remaining zero throughout the code.

I have fixed this issue by ensuring that `env_frictions` and `body_mass` are properly initialized with the correct values. Additionally, I took the opportunity to improve the overall code quality by fixing some errors.

Please pull the latest changes and let me know if you encounter any further issues.

**Comment by Zhangxiaof001** [comment]
good job! thanks!
