### ISSUE TITLE
change terrain

### ISSUE THREAD

**Issue by xiaoyuyinb666** [roboterax/humanoid-gym#42]
hello, authors.Your work are fantastic! I want to know if i wish to change the terrain while running the play.py, like the slope, what should i do?

**Comment by zlw21gxy** [comment]
To enable the use of a triangular mesh for the terrain, uncomment the following line in `play.py`: `env_cfg.terrain.mesh_type = 'trimesh'`. Additionally, you should adjust the terrain type proportions in `humanoid_config.py`. If you want to render a terrain comprised entirely of slopes, set the proportions as follows: `terrain_proportions = [0.0, 0.0, 0.0, 0.5, 0.5, 0.0, 0.0]`.

**Comment by xiaoyuyinb666** [comment]
got it, thank you very much, you are so nice

**Comment by gytrtjyk** [comment]
您好，我已经取消注释了
为什么在运行时地形还是平地

**Comment by 242726Yuncheng** [comment]
您好，我想知道您现在更换地形成功了吗，更换之后训练效果怎么样呢

**Comment by gytrtjyk** [comment]
还可以



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年02月25日 13:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [roboterax/humanoid-gym] change terrain (Issue #42) |

您好，我想知道您现在更换地形成功了吗，更换之后训练效果怎么样呢

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

242726Yuncheng left a comment (roboterax/humanoid-gym#42)

您好，我想知道您现在更换地形成功了吗，更换之后训练效果怎么样呢
