### ISSUE TITLE
Are you planning to expand to isaac lab or not?

### ISSUE THREAD

**Issue by Jaebak1996** [roboterax/humanoid-gym#45]
Dear author.

Recently I‘ve found out this interesting project and checked this repository  is based on Isaac gym. As I know, Nvidia stop to update Isaac gym and now they focus on new simulator, Isaac lab. Do you have any plans to expand or switch the code for Isaac lab? If so, can you tell me when you plan to update it?

Thank you for your open source library.

**Comment by zlw21gxy** [comment]
Yes, in the long term, we plan to make this transition, but because IsaacLab is currently in active development and many academic works are still utilizing Isaac Gym, we need to find the best approach to transferring to IsaacLab. As long as you don't use camera rendering, Isaac Gym is sufficiently functional for your needs.
