### ISSUE TITLE
How to implement parallel training on a multi-GPU server？

### ISSUE THREAD

**Issue by 242726Yuncheng** [roboterax/humanoid-gym#51]

**Comment by zlw21gxy** [comment]
This may present challenges since we do not support multi-GPU training at the initial design stage. Modern GPUs can efficiently handle between 8,000 to 20,000 environments, so adding more may not yield significant benefits. If you are determined to pursue this, you can use [RL-games PPO](https://github.com/Denys88/rl_games) instead of the PPO available in our repository, but please note that it will require some additional work.

**Comment by 242726Yuncheng** [comment]
ok,thanks so much



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 25, 2024 15:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [roboterax/humanoid-gym] How to implement parallel training on a multi-GPU server？ (Issue #51)




 
This may present challenges since we do not support multi-GPU training at the initial design stage. Modern GPUs can efficiently handle between 8,000 to 20,000 environments, so adding more may not yield significant benefits. If you are determined to pursue this, you can use RL-games PPO instead of the PPO available in our repository, but please note that it will require some additional work.
